---
title: "Data Cleaning"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

```{r, message=FALSE}
library(tidyverse)
library(tidyxl)
library(unpivotr)
```

```{r}
path_2 = "data/raw/2_invitro_ph/20190604_ph_response_2.xlsx"
fusa_cells_2 = xlsx_cells(path_2, sheets = 2)
pyth_cells_2 = xlsx_cells(path_2, sheets = 3)
    
```

```{r}
fusa_tidy_2 =
    fusa_cells_2 %>%
    filter(!is_blank & row <= 73) %>%
    # Remove unnecessary information
    behead("up-left", "start_date") %>%
    behead("up-left", "day") %>%
    behead("up", "dimension") %>%
    # Calculate mean and growth rate later
    filter(!dimension %in% c("Mean (cm)", "Growth rate (cm/day)")) %>%
    behead("left-up", "ph") %>%
    behead("left", "replicate") %>%
    rename(length_cm = numeric) %>%
    mutate(
        dimension = recode(dimension, `W (cm)` = "x", `L (cm)` = "y"),
        ph = recode(ph, `Control (1)` = "control", `Control (2)` = "control_2"),
        day = str_extract(day, r"(\d+)")
    ) %>%
    add_column(trial = 2,
               species = "fusarium_oxysporum") %>%
    pivot_wider(
        id_cols = c(start_date, trial, species, ph, replicate, day, comment),
        names_from = dimension,
        values_from = length_cm,
        names_sort = TRUE
    )
```

```{r}
pyth_tidy_2 =
    pyth_cells_2 %>%
    filter(!is_blank & row <= 73) %>%
    behead("up-left", "start_date") %>%
    behead("up-left", "day") %>%
    behead("up", "dimension") %>%
    # Calculate mean and growth rate later
    filter(!dimension %in% c("Mean (cm)", "Cm/day")) %>%
    behead("left-up", "ph") %>%
    behead("left", "replicate") %>%
    rename(length_cm = numeric) %>%
    mutate(
        dimension = recode(dimension, `W (cm)` = "x", `L (cm)` = "y"),
        ph = recode(ph, `Control (1)` = "control", `Control (2)` = "control_2"),
        day = str_extract(day, r"(\d+)")
    ) %>%
    add_column(trial = 2,
               species = "pythium_irregulare") %>%
    pivot_wider(
        id_cols = c(start_date, trial, species, ph, replicate, day, comment),
        names_from = dimension,
        values_from = length_cm,
        names_sort = TRUE
    )
```

```{r}
path_3 = "data/raw/2_invitro_ph/20190X00_ph_response_3.xlsx"

pyth_cells_3 = lapply(1:5, xlsx_cells, path = path_3)
```

```{r}

pyth_tidy_3 = list()

for (cells in pyth_cells_3) {
    tidy = cells %>%
    filter(!is_blank & row <= 20 & col <= 25) %>%
    behead("up-left", "day") %>%
    behead("left", "comment") %>%
    behead("left", "species") %>%
    behead("left", "ph") %>%
    behead("left", "replicate") %>%
    behead("up", "dimension") %>%
    filter(dimension != "Mean") %>%
    rename(length_cm = numeric, comment = comment.header) %>%
    mutate(
        dimension = recode(dimension, W = "x", L = "y"),
        day = str_extract(day, r"(\d+)"),
        ph = tolower(str_extract(ph, r"(\d+|Control)"))
    ) %>%
    add_column(trial = 3, start_date = NA) %>%
    pivot_wider(
        id_cols = c(start_date, trial, species, ph, replicate, day, comment),
        names_from = dimension,
        values_from = length_cm,
        names_sort = TRUE
    )
    pyth_tidy_3 = append(pyth_tidy_3, list(tidy))
}

pyth_tidy_3 = bind_rows(pyth_tidy_3)
```

```{r}
path_4 = "data/raw/2_invitro_ph/20190919_ph_response_4.xlsx"

pyth_cells_4 = lapply(1:5, xlsx_cells, path = path_4)
```

```{r}
pyth_tidy_4 = list()

for (cells in pyth_cells_4) {
    tidy = cells %>%
    filter(!is_blank) %>%
    behead("up-left", "day") %>%
    behead("left", "comment") %>%
    behead("left", "species") %>%
    behead("left", "ph") %>%
    behead("left", "replicate") %>%
    behead("up", "dimension") %>%
    filter(dimension != "Mean") %>%
    rename(length_cm = numeric, comment = comment.header) %>%
    mutate(
        dimension = recode(dimension, W = "x", L = "y"),
        day = str_extract(day, r"(\d+)"),
        ph = tolower(str_extract(ph, r"(\d+|Control)"))
    ) %>%
    add_column(trial = 4, start_date = "19/09/2019") %>%
    pivot_wider(
        id_cols = c(start_date, trial, species, ph, replicate, day, comment),
        names_from = dimension,
        values_from = length_cm,
        names_sort = TRUE
    )
    pyth_tidy_4 = append(pyth_tidy_4, list(tidy))
}

pyth_tidy_4 = bind_rows(pyth_tidy_4)
```